Add multipath NPR feature and adjust usage formatting

diff --git a/packet-block-storage-attach b/packet-block-storage-attach
--- a/packet-block-storage-attach
+++ b/packet-block-storage-attach
@@ -2,29 +2,49 @@
 # Packet.net block storage auto-attach - dlaube
 
 usage(){
-  echo "usage: $0 [-vh] [volume_name]"
-  echo "	-v		make verbose"
-	echo "	-h		display help"
-	echo "	volume_name	specify the volume name to attach, eg: volume-f9a8a263"
-	exit 1
+  echo "usage: $0 [-vhm] [volume_name]"
+  echo "	-v		Make verbose"
+  echo "	-h		Display help"
+  echo "	-m		Set multipath feature no_path_retry, ex: -m [<fail (default) | queue>]"
+  echo "			If block storage is unreachable, the option "fail" results in FS read-only and "queue" will keep IO in memory buffer until reachable"
+  echo "	volume_name	Specify the volume name to attach, eg: volume-f9a8a263"
+  exit 1
 }
 
 # Get cli options
+#_V=0
+#while getopts "vhV:" OPTION
+#do
+#  case $OPTION in
+#    h) usage
+#       ;;
+#    v) _V=1
+#       ;;
+#  esac
+#done
+
+# Get cli options
 _V=0
-while getopts "vhV:" OPTION
+while getopts "m:vh" OPTION
 do
-  case $OPTION in
-    h) usage
-       ;;
-    v) _V=1
-       ;;
-  esac
+    case $OPTION in
+        v) _V=1;;
+        h) usage;;
+	m) mpnpropt="$OPTARG";;
+        *) exit 1;;
+    esac
 done
 
 shift $(($OPTIND - 1))
 if [ $1 ] ; then
 	target=$1
 fi
+
+# Set multipath no_path_retry default if not set
+if [[ -z "${mpnpropt}" ]]; then
+	mpnpropt="fail"
+fi
+[ $_V -eq 1 ] && echo "Multipath no_path_retry feature option set as '$mpnpropt'"
 
 # Depends on jq
 if [ ! `which jq` ]; then
@@ -107,7 +127,7 @@ function restart_iscsid {
 }
 
 # create the multipath config
-cat << 'EOF_mpconf' > /etc/multipath.conf
+cat <<- EOF_mpconf > /etc/multipath.conf
 defaults {
 
        polling_interval       3
@@ -116,7 +136,7 @@ defaults {
        rr_min_io                    100
        rr_weight                    priorities
        failback                    immediate
-       no_path_retry              fail
+       no_path_retry              $mpnpropt
        user_friendly_names     yes
 
 }
